// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconCarbonChevronLeft: typeof import('~icons/carbon/chevron-left.jsx')['default']
  const IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right.jsx')['default']
  const IconCarbonLight: typeof import('~icons/carbon/light.jsx')['default']
  const IconCarbonMoon: typeof import('~icons/carbon/moon.jsx')['default']
  const IconIonChevronDown: typeof import('~icons/ion/chevron-down.jsx')['default']
  const IconMdiArrowLeft: typeof import('~icons/mdi/arrow-left.jsx')['default']
  const IconMdiArrowRight: typeof import('~icons/mdi/arrow-right.jsx')['default']
  const IconMdiLogout: typeof import('~icons/mdi/logout.jsx')['default']
  const http: typeof import('axios')['default']
  const initReactI18next: typeof import('react-i18next')['initReactI18next']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
