// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconCarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
  const IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
  const IconCarbonLight: typeof import('~icons/carbon/light')['default']
  const IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
  const IconIonChevronDown: typeof import('~icons/ion/chevron-down')['default']
  const IconMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
  const IconMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
  const IconMdiLogout: typeof import('~icons/mdi/logout')['default']
  const http: typeof import('axios')['default']
  const initReactI18next: typeof import('react-i18next')['initReactI18next']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
