import { useThemeValue } from "../../context"

export {default as Row} from './Grid/Row'
export {default as Col} from './Grid/Col'
export {default as Container} from './Grid/Container'
export {default as ConditionalAnimation} from './Animation/ConditionalAnimation'
export {default as Backdrop} from './Backdrop'
export {default as Button} from './Buttons/Button'
export {default as ColoredLink} from './Buttons/ColoredLink'
export {default as FormButton} from './Buttons/FormButton'
export {default as IconButton} from './Buttons/IconButton'
export {default as LinkButton} from './Buttons/LinkButton'
export {default as Card} from './Cards/Card'
export {default as CardLinkButton} from './Cards/CardLinkButton'
export {default as Divider} from './Dividers/Divider'
export {default as LongDivider} from './Dividers/LongDivider'
export {default as ErrorPage404} from './ErrorPages/404'
export {default as ErrorPage500} from './ErrorPages/500'
export {default as ErrorPage403} from './ErrorPages/403'
export {default as ErrorPage404ServerSide} from './ErrorPages/404ServerSide'
export {default as Label} from './Form/Label'
export {default as ConditionalLabel} from './Form/ConditionalLabel'
export {default as HelperText} from './Form/HelperText'
export {default as TextField} from './Form/TextField'
export {default as TextArea} from './Form/TextArea'
export {default as Select} from './Form/Select'
export {default as Main} from './Main/Main'
export {default as Modal} from './Modal'
export {default as Portal} from './Portal'
export {default as ProgressSpinner} from './Progress/ProgressSpinner'
export {default as CubicProgress} from './Progress/CubicProgress'
export {default as SideBar} from './SideBar/SideBar'
export {default as SideBarButton} from './SideBar/SideBarButton'
export {default as SideBarLink} from './SideBar/SideBarLink'
export {default as SideBarLinkWrapper} from './SideBar/SideBarLinkWrapper'
export {default as Skeleton} from './Skeleton'
export {default as Tabs} from './Tabs/Tabs'
export {default as Tab} from './Tabs/Tab'
export {default as ThemeProvider} from './Theme/ThemeProvider'
export {default as ThemeToggle} from './Theme/ThemeToggle'
export {default as Tooltip} from './Tooltip/Tooltip'
export {default as Typography} from './Typograpy/Typogrphy'
export {default as theme} from './Utils/theme'


export const isDark: () => boolean = () => useThemeValue() === 'dark'

export default {}
